"""Make the manuscript LaTeX tables from the benchmark CSV(s).

Outputs:
  * publication/tables/summary_per_variant.csv  (median rmsep, win-rate, p-value vs control)
  * publication/tables/summary_per_dataset.csv  (per-dataset best variant)
  * publication/tables/main_regression.tex      (LaTeX-ready)

Usage::

    python publication/scripts/make_tables.py \
      --csv bench/nicon_v2/benchmark_runs/stack_aom_extended/results.csv \
      --out bench/nicon_v2/publication/tables/ \
      --control Ridge-baseline
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--control", type=str, default="Ridge-baseline")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(args.csv)
    df = df[df["status"].astype(str) == "OK"]

    pivot = df.pivot_table(index=["dataset", "seed"], columns="variant", values="rmsep").dropna()

    rows: list[dict] = []
    if args.control not in pivot.columns:
        print(f"control {args.control!r} not in CSV variants {pivot.columns.tolist()}")
        return 1
    control = pivot[args.control]
    for variant in pivot.columns:
        if variant == args.control:
            continue
        treatment = pivot[variant]
        delta = (treatment - control) / control
        wins = int((treatment < control).sum())
        losses = int((treatment > control).sum())
        try:
            stat, p = wilcoxon(treatment, control, zero_method="zsplit")
        except ValueError:
            stat, p = float("nan"), float("nan")
        rows.append({
            "variant": variant,
            "median_rmsep": float(np.median(treatment)),
            "median_delta_pct": float(np.median(delta) * 100),
            "wins": wins,
            "losses": losses,
            "n_pairs": int(len(treatment)),
            "wilcoxon_p": float(p),
        })
    summary = pd.DataFrame(rows).sort_values("median_delta_pct")
    summary.to_csv(args.out / "summary_per_variant.csv", index=False)

    # LaTeX main table.
    tex_path = args.out / "main_regression.tex"
    with tex_path.open("w") as f:
        f.write("% Generated by publication/scripts/make_tables.py\n")
        f.write(f"% Source: {args.csv}, control: {args.control}\n")
        f.write("\\begin{tabular}{lrrrrr}\n")
        f.write("\\toprule\n")
        f.write("Variant & Median rmsep & Median $\\Delta$\\% & Wins & Losses & Wilcoxon $p$ \\\\ \n")
        f.write("\\midrule\n")
        for r in summary.to_dict("records"):
            f.write(
                f"{r['variant']} & {r['median_rmsep']:.4f} & {r['median_delta_pct']:+.2f} & "
                f"{r['wins']} & {r['losses']} & {r['wilcoxon_p']:.3g} \\\\ \n"
            )
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
    print(f"wrote {args.out / 'summary_per_variant.csv'}")
    print(f"wrote {tex_path}")

    # Per-dataset best.
    per_ds = df.groupby(["dataset", "variant"])["rmsep"].median().unstack()
    if args.control in per_ds.columns:
        ratios = per_ds.div(per_ds[args.control], axis=0) - 1.0
        ratios.to_csv(args.out / "summary_per_dataset.csv")
        print(f"wrote {args.out / 'summary_per_dataset.csv'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
