"""Tests for the opt-in ``nirs4all-methods``-backed operators.

Covers four things:

1. **Packaging / import** — the ``n4m`` binding imports and ``libn4m.so``
   resolves in the intended env (the operator module reports it available).
2. **SNV parity vs the methods bit-exact fixture** — the native SNV matches
   the ``nirs4all-methods`` golden ``snv_v1.json`` fixture (and sklearn) to
   floating-point precision.
3. **SNV→PLS parity vs sklearn** — ``MethodsSNV`` → ``MethodsPLS`` matches
   ``StandardNormalVariate`` → ``PLSRegression`` within tolerance.
4. **Dual-engine execution** — the operators run through the normal nirs4all
   pipeline on BOTH the legacy engine and the dag-ml engine, proving the
   sklearn-contract dispatch path works on each.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

# Skip the WHOLE module when the native binding is absent. The operator package
# imports fine without it (it guards the n4m import and sets METHODS_AVAILABLE
# False), so we must gate on the REAL binding — importorskip("n4m") raises
# Skipped (not a failure) when libn4m / the n4m wheel is not installed.
pytest.importorskip("n4m", reason="nirs4all-methods (n4m binding) not installed")

from nirs4all.operators import methods

pytestmark = pytest.mark.skipif(
    not methods.METHODS_AVAILABLE,
    reason="nirs4all-methods (n4m binding) not available",
)

MethodsSNV = methods.MethodsSNV
MethodsPLS = methods.MethodsPLS

# The methods repo's bit-exact parity fixtures live in the sibling checkout.
_METHODS_FIXTURES = Path("/home/delete/nirs4all/nirs4all-methods/parity/fixtures")


def _hexbe_to_array(hex_list: list[str], rows: int, cols: int) -> np.ndarray:
    """Decode an ``ieee754_binary64_be_hex`` fixture column into an array."""
    buf = b"".join(bytes.fromhex(h) for h in hex_list)
    return np.frombuffer(buf, dtype=">f8").astype(np.float64).reshape(rows, cols)


# ----------------------------------------------------------------------
# 1. Packaging / import
# ----------------------------------------------------------------------


class TestPackaging:
    def test_methods_available(self) -> None:
        assert methods.METHODS_AVAILABLE is True

    def test_libn4m_resolves(self) -> None:
        import n4m

        # Loads + queries the embedded libn4m; raises if the .so cannot resolve.
        assert n4m.abi_version()
        assert Path(n4m.library_path()).exists()

    def test_operators_are_fqn_importable(self) -> None:
        # The dag-ml path imports operators by fully-qualified name; the FQN
        # must resolve back to the same classes.
        import importlib

        mod = importlib.import_module(MethodsSNV.__module__)
        assert getattr(mod, MethodsSNV.__qualname__) is MethodsSNV
        assert getattr(mod, MethodsPLS.__qualname__) is MethodsPLS

    def test_params_are_json_serializable(self) -> None:
        json.dumps(MethodsSNV(ddof=1).get_params())
        json.dumps(MethodsPLS(n_components=3, cv=4).get_params())

    def test_set_params_validates_unknown_keys(self) -> None:
        # sklearn-contract: set_params with a real param is reflected in
        # get_params; an unknown param raises ValueError (no silent setattr).
        snv = MethodsSNV()
        snv.set_params(ddof=1, with_std=False)
        assert snv.get_params()["ddof"] == 1
        assert snv.get_params()["with_std"] is False

        pls = MethodsPLS()
        pls.set_params(n_components=7, cv=3)
        assert pls.get_params()["n_components"] == 7
        assert pls.get_params()["cv"] == 3

        with pytest.raises(ValueError):
            MethodsSNV().set_params(not_a_param=1)
        with pytest.raises(ValueError):
            MethodsPLS().set_params(bogus=2)


# ----------------------------------------------------------------------
# 2. SNV parity vs the methods bit-exact fixture
# ----------------------------------------------------------------------


@pytest.mark.skipif(
    not (_METHODS_FIXTURES / "snv_v1.json").exists(),
    reason="methods snv_v1 fixture not present",
)
class TestSNVFixtureParity:
    def test_snv_matches_methods_golden_fixture(self) -> None:
        fixture = json.loads((_METHODS_FIXTURES / "snv_v1.json").read_text())
        rows, cols = fixture["rows"], fixture["cols"]
        X = _hexbe_to_array(fixture["input_hex"], rows, cols)

        for case in fixture["cases"]:
            params = case["params"]
            expected = _hexbe_to_array(case["output_hex"], rows, cols)
            got = MethodsSNV(**params).fit_transform(X)
            # The golden output was generated by the 0.9.1 numpy reference; the
            # native engine matches it to floating-point precision.
            np.testing.assert_allclose(got, expected, rtol=0, atol=1e-12)

    def test_snv_matches_sklearn_default(self) -> None:
        fixture = json.loads((_METHODS_FIXTURES / "snv_v1.json").read_text())
        X = _hexbe_to_array(fixture["input_hex"], fixture["rows"], fixture["cols"])
        # Reference SNV: row-wise (x - mean) / std.
        mu = X.mean(axis=1, keepdims=True)
        sd = X.std(axis=1, ddof=0, keepdims=True)
        ref = (X - mu) / sd
        got = MethodsSNV().fit_transform(X)
        np.testing.assert_allclose(got, ref, rtol=0, atol=1e-12)


# ----------------------------------------------------------------------
# 3. SNV → PLS parity vs sklearn
# ----------------------------------------------------------------------


class TestSNVPLSvsSklearn:
    def _data(self) -> tuple[np.ndarray, np.ndarray]:
        fixture_path = _METHODS_FIXTURES / "synthetic_small_pls2_v1.json"
        if fixture_path.exists():
            fixture = json.loads(fixture_path.read_text())

            def _arr(o: dict) -> np.ndarray:
                return np.asarray(o["values"], dtype=np.float64).reshape(o["shape"])

            X = _arr(fixture["data"]["X"])
            y = _arr(fixture["data"]["Y"])[:, 0]  # single target -> PLS1
            return X, y
        rng = np.random.default_rng(7)
        X = rng.standard_normal((60, 24))
        y = X[:, 0] - 0.4 * X[:, 5] + 0.02 * rng.standard_normal(60)
        return X, y

    def test_pls_matches_sklearn_on_common_input(self) -> None:
        from sklearn.cross_decomposition import PLSRegression

        X, y = self._data()
        # Common SNV input isolates the PLS comparison.
        Xs = MethodsSNV().fit_transform(X)

        methods_pls = MethodsPLS(n_components=3, cv=2, scale_x=True).fit(Xs, y)
        pred_methods = methods_pls.predict(Xs)

        sk = PLSRegression(n_components=3, scale=True).fit(Xs, y)
        pred_sklearn = sk.predict(Xs).ravel()

        max_diff = float(np.max(np.abs(pred_methods - pred_sklearn)))
        assert max_diff < 1e-9, f"methods vs sklearn PLS pred max|diff|={max_diff:.3e}"

    def test_full_snv_pls_pipeline_matches_sklearn(self) -> None:
        from sklearn.cross_decomposition import PLSRegression

        from nirs4all.operators.transforms import StandardNormalVariate

        X, y = self._data()

        # Methods pipeline.
        Xs_m = MethodsSNV().fit_transform(X)
        pred_m = MethodsPLS(n_components=3, cv=2, scale_x=True).fit(Xs_m, y).predict(Xs_m)

        # Pure-Python nirs4all SNV + sklearn PLS pipeline.
        Xs_p = StandardNormalVariate().fit_transform(X)
        pred_p = PLSRegression(n_components=3, scale=True).fit(Xs_p, y).predict(Xs_p).ravel()

        rmse_m = float(np.sqrt(np.mean((pred_m - y) ** 2)))
        rmse_p = float(np.sqrt(np.mean((pred_p - y) ** 2)))
        assert abs(rmse_m - rmse_p) < 1e-6
        np.testing.assert_allclose(pred_m, pred_p, rtol=0, atol=1e-8)


# ----------------------------------------------------------------------
# 4. Dual-engine execution
# ----------------------------------------------------------------------


class TestDualEngine:
    def _pipeline(self) -> list:
        from sklearn.model_selection import ShuffleSplit

        return [
            MethodsSNV(),
            ShuffleSplit(n_splits=2, random_state=0),
            {"model": MethodsPLS(n_components=5, cv=2)},
        ]

    @pytest.mark.parametrize("engine", ["legacy", "dag-ml"])
    def test_runs_under_engine(self, engine: str) -> None:
        import nirs4all

        # Single-target corpus: the native engine is PLS1 (single-output).
        dataset = nirs4all.generate.regression(n_samples=80, random_state=0, target_component=0)
        result = nirs4all.run(
            pipeline=self._pipeline(),
            dataset=dataset,
            engine=engine,
            verbose=0,
        )
        assert result is not None
        assert hasattr(result, "best_rmse")
        assert np.isfinite(result.best_rmse)
        assert result.best_rmse > 0
