# Pipeline 5: Stacking and Merge with Meta-Model
#
# Features covered:
# - Named branches with different model types
# - merge keyword with predictions mode
# - Per-branch model selection (best, top_k)
# - MetaModel for stacking
# - Multi-level stacking architecture
#
# This pipeline demonstrates ensemble stacking via prediction merging.

pipeline:
  # Step 1: Feature scaling
  - class: sklearn.preprocessing.MinMaxScaler

  # Step 2: Target scaling
  - y_processing:
      class: sklearn.preprocessing.StandardScaler

  # Step 3: Cross-validation
  - class: sklearn.model_selection.KFold
    params:
      n_splits: 5
      shuffle: true
      random_state: 42

  # Step 4: Branched model training
  - branch:
      pls_branch:
        # Multiple PLS variants
        - class: nirs4all.operators.transforms.StandardNormalVariate
        - model:
            class: sklearn.cross_decomposition.PLSRegression
            params:
              n_components: 5
          name: PLS-5
        - model:
            class: sklearn.cross_decomposition.PLSRegression
            params:
              n_components: 10
          name: PLS-10
        - model:
            class: sklearn.cross_decomposition.PLSRegression
            params:
              n_components: 15
          name: PLS-15

      rf_branch:
        # Random Forest with different depths
        - class: nirs4all.operators.transforms.MultiplicativeScatterCorrection
        - model:
            class: sklearn.ensemble.RandomForestRegressor
            params:
              n_estimators: 50
              max_depth: 5
              random_state: 42
          name: RF-shallow
        - model:
            class: sklearn.ensemble.RandomForestRegressor
            params:
              n_estimators: 100
              max_depth: 10
              random_state: 42
          name: RF-deep

      ridge_branch:
        # Ridge regression with PCA
        - class: nirs4all.operators.transforms.FirstDerivative
        - class: sklearn.decomposition.PCA
          params:
            n_components: 20
        - model:
            class: sklearn.linear_model.Ridge
            params:
              alpha: 0.1
          name: Ridge-PCA
        - model:
            class: sklearn.linear_model.Ridge
            params:
              alpha: 1.0
          name: Ridge-Strong

  # Step 5: Merge predictions for stacking
  # Select best models from each branch for the meta-learner
  - merge:
      predictions:
        - branch: 0  # pls_branch
          select: best
          metric: rmse
        - branch: 1  # rf_branch
          select:
            top_k: 2
          metric: rmse
        - branch: 2  # ridge_branch
          select: all
      features:
        - 0  # Include features from pls_branch
      output_as: features
      on_missing: warn

  # Step 6: Meta-learner trained on stacked predictions
  - model:
      class: nirs4all.operators.models.MetaModel
      params:
        model:
          class: sklearn.linear_model.Ridge
          params:
            alpha: 0.5
        source_models: all
    name: Meta-Ridge

  # Step 7: Another meta-learner for comparison
  - model:
      class: sklearn.ensemble.RandomForestRegressor
      params:
        n_estimators: 30
        max_depth: 5
        random_state: 42
    name: Meta-RF
